"""
SQLAlchemy models for the AI Content Agent System.
"""
from datetime import datetime
from typing import Optional, List
from sqlalchemy import (
    Column, Integer, String, DateTime, Boolean, 
    Text, ForeignKey, JSON, Enum
)
from sqlalchemy.orm import relationship
from sqlalchemy.sql import func
import enum

from app.database import Base


# =============== ENUMS ===============
class UserRole(str, enum.Enum):
    ADMIN = "admin"
    REVIEWER = "reviewer"
    CLIENT = "client"


class ContentStatus(str, enum.Enum):
    DRAFT = "draft"
    PENDING_REVIEW = "pending_review"
    APPROVED = "approved"
    REJECTED = "rejected"
    CHANGES_REQUESTED = "changes_requested"
    SCHEDULED = "scheduled"
    PUBLISHED = "published"
    ARCHIVED = "archived"
    CANCELLED = "cancelled"


class ApprovalStatus(str, enum.Enum):
    PENDING = "pending"
    APPROVED = "approved"
    REJECTED = "rejected"
    CHANGES_REQUESTED = "changes_requested"


class SystemMode(str, enum.Enum):
    NORMAL = "normal"
    MANUAL = "manual"
    CRISIS = "crisis"


class Platform(str, enum.Enum):
    LINKEDIN = "linkedin"
    INSTAGRAM = "instagram"
    TWITTER = "twitter"


# =============== MODELS ===============
class User(Base):
    """User model for authentication and authorization."""
    __tablename__ = "users"
    
    id = Column(Integer, primary_key=True, index=True)
    email = Column(String, unique=True, index=True, nullable=False)
    hashed_password = Column(String, nullable=False)
    full_name = Column(String, nullable=True)
    role = Column(Enum(UserRole), default=UserRole.CLIENT)
    is_active = Column(Boolean, default=True)
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), onupdate=func.now())
    
    # Relationships
    content_drafts = relationship("ContentDraft", back_populates="author")
    approval_requests = relationship("ApprovalRequest", back_populates="reviewer")
    audit_logs = relationship("AuditLog", back_populates="user")


class BrandVoice(Base):
    """Brand voice configuration for content generation."""
    __tablename__ = "brand_voices"
    
    id = Column(Integer, primary_key=True, index=True)
    name = Column(String, nullable=False)
    description = Column(Text, nullable=True)
    config = Column(JSON, nullable=False)  # JSON configuration
    is_active = Column(Boolean, default=True)
    created_by = Column(Integer, ForeignKey("users.id"))
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), onupdate=func.now())
    
    # Relationships
    content_drafts = relationship("ContentDraft", back_populates="brand_voice")


class MediaAsset(Base):
    """Uploaded media assets (images, videos)."""
    __tablename__ = "media_assets"
    
    id = Column(Integer, primary_key=True, index=True)
    filename = Column(String, nullable=False)
    filepath = Column(String, nullable=False)
    mime_type = Column(String, nullable=False)
    size_bytes = Column(Integer, nullable=False)
    metadata = Column(JSON, nullable=True)  # EXIF, dimensions, etc.
    uploaded_by = Column(Integer, ForeignKey("users.id"))
    created_at = Column(DateTime(timezone=True), server_default=func.now())


class ContentDraft(Base):
    """Content draft generated by AI."""
    __tablename__ = "content_drafts"
    
    id = Column(Integer, primary_key=True, index=True)
    platform = Column(Enum(Platform), nullable=False)
    content_text = Column(Text, nullable=False)
    hashtags = Column(JSON, nullable=True)  # List of hashtags
    media_assets = Column(JSON, nullable=True)  # List of media asset IDs
    brand_voice_id = Column(Integer, ForeignKey("brand_voices.id"))
    status = Column(Enum(ContentStatus), default=ContentStatus.DRAFT)
    generated_context = Column(JSON, nullable=True)  # Context used for generation
    created_by = Column(Integer, ForeignKey("users.id"))
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), onupdate=func.now())
    
    # Relationships
    author = relationship("User", back_populates="content_drafts")
    brand_voice = relationship("BrandVoice", back_populates="content_drafts")
    approval_requests = relationship("ApprovalRequest", back_populates="content_draft")
    scheduled_posts = relationship("ScheduledPost", back_populates="content_draft")


class ApprovalRequest(Base):
    """Approval workflow requests."""
    __tablename__ = "approval_requests"
    
    id = Column(Integer, primary_key=True, index=True)
    content_draft_id = Column(Integer, ForeignKey("content_drafts.id"), nullable=False)
    requested_by = Column(Integer, ForeignKey("users.id"))
    requested_at = Column(DateTime(timezone=True), server_default=func.now())
    reviewer_id = Column(Integer, ForeignKey("users.id"), nullable=True)
    status = Column(Enum(ApprovalStatus), default=ApprovalStatus.PENDING)
    comments = Column(Text, nullable=True)
    reviewed_at = Column(DateTime(timezone=True), nullable=True)
    
    # Relationships
    content_draft = relationship("ContentDraft", back_populates="approval_requests")
    requester = relationship("User", foreign_keys=[requested_by])
    reviewer = relationship("User", foreign_keys=[reviewer_id], back_populates="approval_requests")


class ScheduledPost(Base):
    """Scheduled social media posts."""
    __tablename__ = "scheduled_posts"
    
    id = Column(Integer, primary_key=True, index=True)
    content_draft_id = Column(Integer, ForeignKey("content_drafts.id"), nullable=False)
    platform = Column(Enum(Platform), nullable=False)
    scheduled_for = Column(DateTime(timezone=True), nullable=False)
    posted_at = Column(DateTime(timezone=True), nullable=True)
    status = Column(String, default="pending")  # pending, posted, failed, cancelled
    post_id = Column(String, nullable=True)  # Platform post ID
    error_message = Column(Text, nullable=True)
    metrics = Column(JSON, nullable=True)  # Engagement metrics
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    
    # Relationships
    content_draft = relationship("ContentDraft", back_populates="scheduled_posts")


class SystemStatus(Base):
    """System-wide status and control settings."""
    __tablename__ = "system_status"
    
    id = Column(Integer, primary_key=True)
    mode = Column(Enum(SystemMode), default=SystemMode.NORMAL)
    is_paused = Column(Boolean, default=False)
    last_updated_by = Column(Integer, ForeignKey("users.id"), nullable=True)
    last_updated_at = Column(DateTime(timezone=True), onupdate=func.now())
    notes = Column(Text, nullable=True)
    
    # Relationships
    updated_by_user = relationship("User")


class AuditLog(Base):
    """Audit log for all system actions."""
    __tablename__ = "audit_logs"
    
    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(Integer, ForeignKey("users.id"), nullable=True)
    action = Column(String, nullable=False)
    entity_type = Column(String, nullable=False)  # user, content_draft, etc.
    entity_id = Column(Integer, nullable=True)
    details = Column(JSON, nullable=True)
    ip_address = Column(String, nullable=True)
    user_agent = Column(String, nullable=True)
    timestamp = Column(DateTime(timezone=True), server_default=func.now())
    
    # Relationships
    user = relationship("User", back_populates="audit_logs")
